# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 03:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'catalog',
            },
        ),
        migrations.CreateModel(
            name='Itemlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('smalllpicurl', models.CharField(max_length=100)),
                ('bigpicurl', models.CharField(max_length=100)),
                ('addtime', models.DateTimeField(default=datetime.datetime(2016, 12, 29, 3, 15, 44, 510819, tzinfo=utc))),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm.Catalog')),
            ],
            options={
                'db_table': 'itemlist',
            },
        ),
    ]
